version: "3.9"

services:
  postgres:
    image: postgres
    restart: always
    container_name: ecommerce-development-postgres
    ports:
      - 5432:5432
    env_file:
      - .env.local
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
